update to work with K8up 1.0+
projectsyn/component-backup-k8up pull request #20
Opened 2021-02-16 08:47 UTC by splattner

* Deploy CRD's befor Helm chart
* Update for changed Helm values

Solves #17

## Checklist

- [x] Keep pull requests small so they can be easily reviewed.
- [x] Update the documentation.
- [x] Update the ./CHANGELOG.md.
- [x] Link this PR to related issues.

2021-02-16 14:53 UTC, srueg requested changes

2021-02-16 14:53 UTC, srueg commented on class/backup-k8up.yml
> +        output_path: dependencies/backup-k8up/crds/02_k8up_crds.yaml
```suggestion
        output_path: dependencies/backup-k8up/crds/${backup_k8up:charts:k8up}/02_k8up_crds.yaml
```

2021-02-16 14:53 UTC, srueg commented on class/backup-k8up.yml
> +          - dependencies/backup-k8up/crds
```suggestion
          - dependencies/backup-k8up/crds/v${backup_k8up:charts:k8up}/
```

2021-02-16 14:53 UTC, srueg commented on class/backup-k8up.yml
> +        output_path: dependencies/backup-k8up/crds/02_k8up_crds.yaml
Otherwise a new version won't be downloaded if the target already exists on disk.

2021-02-16 14:53 UTC, srueg commented on class/backup-k8up.yml
>              backupImage:
We should probably expose the resource requests/limits in the `config.yml` to make them configurable.

2021-02-16 14:56 UTC, ccremer requested changes

2021-02-16 14:56 UTC, ccremer commented on class/backup-k8up.yml
> +        output_path: dependencies/backup-k8up/crds/02_k8up_crds.yaml
This needs to be kind of configurable. The CRDs for K8s 1.16+ are not compatible with OpenShift 3.11, so for OCP 3.11 we need to download the legacy crd file.

2021-02-16 14:56 UTC, ccremer commented on class/defaults.yml
> +        tag: 'v1.0.0@sha256:444fdff25c401dd312116e8b2e4813d61ac6c88656b50c888dbc00f0d2f7ecd4'
We just released v1.0.1 :)

2021-02-16 15:02 UTC, ccremer commented on class/backup-k8up.yml
>              backupImage:
Are all helm values automatically exposed? what about leader election, timezone, etc?

2021-02-16 15:07 UTC, splattner commented on class/backup-k8up.yml
> +        output_path: dependencies/backup-k8up/crds/02_k8up_crds.yaml
I'll look into this and figure out a way to make this configurable

2021-02-16 15:10 UTC, splattner commented on class/backup-k8up.yml
>              backupImage:
no, not all are exposed automatically.
Timezone is, leader election is not. 
I can add reqouse request/limits and the leader election flag :+1:

2021-02-16 15:10 UTC, srueg commented on class/backup-k8up.yml
>              backupImage:
No, they're not. We could just do `helm_values: ${${backup_k8up:helmValues}}` and then have all values in `config.yml` and therefore exposed...

2021-02-16 15:11 UTC, splattner commented on class/defaults.yml
> +        tag: 'v1.0.0@sha256:444fdff25c401dd312116e8b2e4813d61ac6c88656b50c888dbc00f0d2f7ecd4'
nice :+1:  I just changed it to v1.0.1

2021-02-16 15:23 UTC, splattner commented on class/backup-k8up.yml
> +        output_path: dependencies/backup-k8up/crds/02_k8up_crds.yaml
I made the CRD filename a parameter which defaults to `k8up-crd.yaml` + documentation.

2021-02-16 15:39 UTC, ccremer commented on class/backup-k8up.yml
>              backupImage:
Be aware that there are 2 types of resources: The ones that K8up Pod should use itself, and the ones that are used for K8up-spawned Pods (Backup, prunes, etc.). See https://k8up.io/k8up/1.0.0/how-tos/manage-pod-resources.html. The chart supports this via [k8up.globalResources](https://github.com/appuio/charts/blob/master/k8up/values.yaml#L57) parameter

2021-02-16 15:47 UTC, ccremer commented on class/backup-k8up.yml
>              backupImage:
Also `replicaCount`. Some customers with large clusters/many schedules may be interested to have hot-standby pods (requires leader election)

2021-02-17 08:56 UTC, splattner commented on class/backup-k8up.yml
>              backupImage:
I introduces the variable `helmValues` and reused most of the existing parameter (e.g. all the envVars) and put them into the helmValues dict. So when using the default `helmValues` the other already existing parameters can be reused.

2021-02-17 09:58 UTC, srueg commented on docs/modules/ROOT/pages/references/parameters.adoc
> +Values passend to Helm.
Please add a link to the docs: https://github.com/appuio/charts/tree/master/k8up

2021-02-17 10:16 UTC, splattner commented on docs/modules/ROOT/pages/references/parameters.adoc
> +Values passend to Helm.
:+1:

2021-02-17 11:03 UTC, ccremer commented on class/defaults.yml
> +        timezone: "Europe/Zurich"
btw, #1 asks for this default to be changed to UTC

2021-02-17 12:05 UTC, splattner commented on class/defaults.yml
> +        timezone: "Europe/Zurich"
Shall I change it here, or does it need more time and then change it in #1 ?

2021-02-17 12:09 UTC, ccremer commented on class/defaults.yml
> +        timezone: "Europe/Zurich"
I would argue that since this PR is doing breaking changes, we might also introduce a "breaking" change of default values. So when people look up to see what has changed in order to make the component work again, they notice that not only parameters have changed, but also an important default value. I would avoid a second breaking change if possible.

2021-02-17 12:44 UTC, srueg approved these changes

2021-02-17 13:50 UTC, ccremer approved these changes

2021-02-17 13:52 UTC, ccremer commented on CHANGELOG.md
> +- Upgrade K8up chart to v1.0 release ([#20])
Actually, missing here is the change of default value I guess?

2021-02-17 14:07 UTC, splattner commented on CHANGELOG.md
> +- Upgrade K8up chart to v1.0 release ([#20])
no, its currently still set to "Europe/Zurich", no change there. The difference is, now its his own Helm value which in the Helm template is used to create an new env var item for the container. Before it was directly in the envVars passed to Helm.

But I will add "Expose all Helm values" to the list, as this is a change.

2021-02-17 14:10 UTC, splattner commented on CHANGELOG.md
> +- Upgrade K8up chart to v1.0 release ([#20])
well, but yes, the `tz` parameter is gone, and now its in the `helmValues`parameter, I add this to the changelog

2021-02-17 15:33 UTC, ccremer commented on CHANGELOG.md
> +- Upgrade K8up chart to v1.0 release ([#20])
I'm not sure what you mean. The `tz` parameter is still set to Europe/Zurich in `class/defaults.yml`?

2021-02-17 15:42 UTC, splattner commented on CHANGELOG.md
> +- Upgrade K8up chart to v1.0 release ([#20])
oh damm.. i think I messed up my last commit which squashing my commits.... let me fix..

2021-02-17 15:44 UTC, splattner commented on CHANGELOG.md
> +- Upgrade K8up chart to v1.0 release ([#20])
ok.. fixed again.

https://github.com/projectsyn/component-backup-k8up/pull/20/files#diff-6fd07ea8eb879a940d3dfb5e2d4f7bcb6f049795bc05fbd7f2dbbb7bc2f5c310R19

vs

https://github.com/projectsyn/component-backup-k8up/pull/20/files#diff-6fd07ea8eb879a940d3dfb5e2d4f7bcb6f049795bc05fbd7f2dbbb7bc2f5c310L34

2021-02-17 15:48 UTC, ccremer commented on CHANGELOG.md
> +- Upgrade K8up chart to v1.0 release ([#20])
I think we misunderstand eachother :see_no_evil: #1 is about changing the default value from **Zurich** to **UTC**

2021-02-17 16:01 UTC, splattner commented on CHANGELOG.md
> +- Upgrade K8up chart to v1.0 release ([#20])
Oh, I probably understood your comment in https://github.com/projectsyn/component-backup-k8up/pull/20#discussion_r577559545 wrong :see_no_evil: . So you don't want an other breaking change in #1 right? and instead doing it here, as its anyway a breaking change? :)

2021-02-17 16:03 UTC, ccremer commented on CHANGELOG.md
> +- Upgrade K8up chart to v1.0 release ([#20])
yes, exactly :)

2021-02-17 16:07 UTC, splattner commented on CHANGELOG.md
> +- Upgrade K8up chart to v1.0 release ([#20])
done :+1:

2021-02-17 16:37 UTC, ccremer commented on class/defaults.yml
> +        timezone: "UTC"
Even though `UTC` is in the [list of accepted values](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones), it's an alias of `Etc/UTC`.
Theoretically, if the parameter is empty, the cluster's timezone is used (which is UTC anyway at least on our clusters). But I think we should make this parameter explicit

2021-03-08 13:38 UTC, srueg commented on docs/modules/ROOT/pages/references/parameters.adoc
> +Values passend to Helm. See https://github.com/appuio/charts/tree/master/k8up
```suggestion
Values passed to Helm. See https://github.com/appuio/charts/tree/master/k8up 
```

2021-03-08 14:15 UTC, simu reviewed
I don't see any obvious issues in the change itself, but I'm missing a reference to the K8up 0.x to 1.x migration documentation (https://k8up.io/k8up/1.0.0/how-tos/upgrade.html#_upgrade_k8up_from_0_x_to_1_x), with a accompanying document listing the actual steps required for rolling out K8up 1.x with Commodore on a cluster on which K8up 0.x is already present.

2021-03-10 10:48 UTC, ccremer commented on class/defaults.yml
> -        tag: 'v0.1.9@sha256:6b756ddb70e15977fc3d53a0468bcf6386d79d989768d48696167161f20e115e'
I added an upgrade process that assumes a component migration from v1 to v2 (both tags not existing yet)

2021-03-10 10:51 UTC, simu approved these changes

2021-03-11 09:42 UTC, srueg commented
Please replace `inv.parameters.customer.name` with `inv.parameters.cluster.tenant` in to close #4 

https://github.com/projectsyn/component-backup-k8up/blob/upgrade_v1_0_0/lib/backup-k8up.libjsonnet#L41

2021-03-11 09:54 UTC, ccremer commented
@srueg please have a look at https://github.com/projectsyn/component-backup-k8up/pull/20/commits/8897df9edf145906cfc44a70008c9587b8e1b67a, not sure if I got the right ones (`grep -r customer`)

2021-03-11 10:10 UTC, srueg approved these changes

2021-03-11 10:17 UTC, merged