Upgrade k8up, new alert rules, remove deprecated keepJobs
projectsyn/component-backup-k8up pull request #37
Opened 2021-08-02 16:02 UTC by bastjan

This PR upgrades the `k8up` helm chart to `v1.1.0` and the underlying `k8up` to `v1.2.0`.

It takes the new alert rules from the updated helm chart and replaces the `keepjobs` field with the new `failedJobsHistoryLimit` and `successfulJobsHistoryLimit` fields.

## Checklist

- [x] Keep pull requests small so they can be easily reviewed.
- [ ] Update the documentation.
- [x] Categorize the PR by setting a good title and adding one of the labels:
      `bug`, `enhancement`, `documentation`, `change`, `breaking`, `dependency`
      as they show up in the changelog
- [x] Link this PR to related issues.

2021-08-02 16:06 UTC, bastjan commented on class/defaults.yml
> +      K8upArchiveFailed:
Should we add a `jobFailedTemplate` and `jobFailedRulesFor` fields analogous to the [helm chart](https://github.com/appuio/charts/blob/b3ec4af540e37e1cc56eede890a53314fedb8e28/appuio/k8up/values.yaml#L109)?

WDYT @ccremer ?

2021-08-02 16:24 UTC, ccremer commented on docs/modules/ROOT/pages/references/parameters.adoc
> +  expr: (sum(kube_job_status_failed) by(${backup_k8up:monitoring_kube_state_metrics_job_name_label}, namespace) * on(${backup_k8up:monitoring_kube_state_metrics_job_name_label}, namespace) group_righ
Is it really necessary to duplicate code here? I'd just link to the `default.yml` file.

2021-08-02 16:24 UTC, ccremer commented on class/defaults.yml
> +      K8upArchiveFailed:
I'm not quite sure what you mean. can you post a prosa example?

2021-08-03 07:38 UTC, bastjan commented on class/defaults.yml
> +      K8upArchiveFailed:
Something like in 9cd949cb85d0a5c03834e9e9c225b5071d6dbb30. Not sure if I prefer it. Feels a bit overengineered...

2021-08-03 07:53 UTC, ccremer commented on class/defaults.yml
> +      K8upArchiveFailed:
On first sight with the approach you linked I'd loose the ability to customize a single alert. e.g. changing the severity of the prune alert. On second sight, I could remove "prune" from `jobFailedRulesFor` and copy the template to make my own.

@simu has often brilliant ideas, I say let's summon him :)

2021-08-03 08:20 UTC, simu commented on class/defaults.yml
> +        severity: critical
I'd do something like the following to keep the ability to customize and disable individual alerts while keeping the template:

```suggestion
    # Create JobFailed alert rules for the following types of jobs.
    # Valid values are: ["archive", "backup", "check", "prune", "restore"]
    job_failed_alerts_for: 
      archive:
        enabled: true
        overrides: {}
      backup:
        enabled: true
        overrides: {}
      check:
        enabled: true
        overrides: {}
      prune:
        enabled: true
        overrides: {}
      restore:
        enabled: true
        overrides: {}
    # The template for the JobFailed alert rules.
    # %(type)s in `alert` and `expr` is replaced by the types defined in `job_failed_alerts_for`.
    job_failed_alert_template:
      alert: K8up%(type)sFailed
      annotations:
        summary: Job in {{ $labels.namespace }} of type {{ $labels.label_k8up_syn_tools_type }} failed
      expr: (sum(kube_job_status_failed) by(${backup_k8up:monitoring_kube_state_metrics_job_name_label}, namespace) * on(${backup_k8up:monitoring_kube_state_metrics_job_name_label}, namespace) group_right() kube_job_labels{label_k8up_syn_tools_type="%(type)s"}) > 0
      for: 1m
      labels:
        severity: critical
```

2021-08-03 08:20 UTC, simu commented on component/monitoring.jsonnet
> +
Change this to something like the following to use the new suggested structure:

```suggestion
local render_failed_job_alert(type) =
  local alertconfig = params.job_failed_alerts_for[type];
  if alertconfig.enabled then
    params.job_failed_alert_template {
      alert: params.job_failed_alert_template.alert % { type: asciiTitleCase(type) },
      expr: params.job_failed_alert_template.expr % { type: type },
    } + alertconfig.overrides
  else
    null;
  
local failed_job_alert_rules = std.filter(
  function(it) it != null,
  std.map(
    render_failed_job_alert,
    std.objectFields(params.job_failed_alerts_for)
  )
);

```

2021-08-03 08:20 UTC, simu commented on component/monitoring.jsonnet
> +    expr: params.job_failed_alert_template.expr % { type: type },
These might work as just

```suggestion
    alert: super.alert % { type: asciiTitleCase(type) },
    expr: super.expr % { type: type },
```

but I'm never sure in which contexts Jsonnet provides `super`.

2021-08-03 08:21 UTC, simu commented on class/defaults.yml
> +      K8upArchiveFailed:
I added my idea as suggestions. tl;dr: make `job_failed_alerts_for` an object with entries for each alert type and use that to control whether to create the alert and to allow users to provide overrides for single alerts.

2021-08-03 08:22 UTC, bastjan commented on class/defaults.yml
> +      K8upArchiveFailed:
Looks great! Thanks for the input 😊

2021-08-03 11:04 UTC, bastjan commented on component/monitoring.jsonnet
> +    expr: params.job_failed_alert_template.expr % { type: type },
works indeed! TIL

2021-08-03 11:13 UTC, simu requested changes
The failed job alert rendering needs to be documented in `docs/modules/ROOT/pages/references/parameters.adoc`.

I've added some smaller remarks as inline comments

2021-08-03 11:13 UTC, simu commented on class/defaults.yml
> +    # Valid values are: ["archive", "backup", "check", "prune", "restore"]
Comment probably should be updated to describe the new structure

2021-08-03 11:13 UTC, simu commented on class/defaults.yml
> +      failed_jobs_history_limit: ''
What does K8up do when the environment variables are present with an empty string as the value?

2021-08-03 11:13 UTC, simu commented on docs/modules/ROOT/pages/references/parameters.adoc
> +
Probably worth to actually describe what we're configuring here, and what the default behavior is

2021-08-03 11:13 UTC, simu commented on component/monitoring.jsonnet
> +    null;
Might be worth to only process the alert rule types that we officially support, something like:

```suggestion
local failed_job_types = ['archive', 'backup', 'check', 'prune', 'restore'];
local render_failed_job_alert(type) =
  local alertconfig = params.job_failed_alerts_for[type];
  if std.member(failed_job_types, type) && alertconfig.enabled then
    params.job_failed_alert_template + alertconfig.overrides + {
      alert: super.alert % { type: asciiTitleCase(type) },
      expr: super.expr % { type: type },
    }
  else
    null;
```

Or go all the way and throw an error for unknown failed_job types

```suggestion
local failed_job_types = ['archive', 'backup', 'check', 'prune', 'restore'];
local render_failed_job_alert(type) =
  assert std.member(failed_job_types, type) : 'Unknown failed job type "%s"' % type;
  local alertconfig = params.job_failed_alerts_for[type];
  if alertconfig.enabled then
    params.job_failed_alert_template + alertconfig.overrides + {
      alert: super.alert % { type: asciiTitleCase(type) },
      expr: super.expr % { type: type },
    }
  else
    null;
```

2021-08-03 11:15 UTC, bastjan commented on component/monitoring.jsonnet
> +    null;
> Or go all the way and throw an error for unknown failed_job types

i prefer it this way!

2021-08-03 12:18 UTC, ccremer commented on class/defaults.yml
> +      failed_jobs_history_limit: ''
It overrides the hardcoded fallback value of `3` to `0`.

2021-08-03 12:26 UTC, bastjan commented on class/defaults.yml
> +      failed_jobs_history_limit: ''
Jep just saw it too. We could use `-1` which falls back to keepjobs or embrace the new variables which would be a breaking change in my mind...

2021-08-03 12:26 UTC, simu commented on class/defaults.yml
> +      failed_jobs_history_limit: ''
In that case it might be preferable to default to `null`, so the environment variables are not configured unless these parameters are set. See the postprocessing filter for the logic which removes all environment variables with `value: null`: https://github.com/projectsyn/component-backup-k8up/blob/77aecc740f283f6926dba336282a043eba88bd42/postprocess/optional_global_config.jsonnet#L28-L51

2021-08-03 12:29 UTC, bastjan commented on class/defaults.yml
> +      failed_jobs_history_limit: ''
That's exactly what i looked for! 🤦‍♀️ 

Sadly postprocessing filters do not yet work when running `make test` because of a wrong search path implementation for them. But good enough for now.

2021-08-03 12:56 UTC, simu requested changes
Implementation mostly LGTM. I've left a bunch of comments for the documentation changes.

2021-08-03 12:56 UTC, simu commented on component/monitoring.jsonnet
> +    }
Probably a good idea to allow merging of configs, e.g. to add labels or annotations on individual alerts:

```suggestion
    com.makeMergeable(params.job_failed_alert_template) + 
    com.makeMergeable(alertconfig.overrides) + 
    {
      alert: super.alert % { type: asciiTitleCase(type) },
      expr: super.expr % { type: type },
    }
```

With the current setup, setting `overrides.labels` for an alert would replace the existing labels coming from the alert template.

2021-08-03 12:56 UTC, simu commented on docs/modules/ROOT/pages/references/parameters.adoc
> +Overrides `global_backup_config.keepjobs`.
```suggestion
Overrides `global_backup_config.keepjobs`.
If neither `global_backup_config.keepjobs` nor this parameter are set, the [K8up default value|link to K8up docs?] for the configuration is used.
```

Would be nice if I was told what the default value is when reading the component parameter docs, either directly or through a link to the relevant K8up documentation.

2021-08-03 12:56 UTC, simu commented on docs/modules/ROOT/pages/references/parameters.adoc
> +Overrides `global_backup_config.keepjobs`.
Same here as for `successful_jobs_history_limit`

2021-08-03 12:56 UTC, simu commented on docs/modules/ROOT/pages/references/parameters.adoc
> +default:: See https://github.com/projectsyn/component-backup-k8up/blob/master/class/defaults.yml
```suggestion
default:: [See `class/defaults.yml`|https://github.com/projectsyn/component-backup-k8up/blob/master/class/defaults.yml]
```

2021-08-03 12:56 UTC, simu commented on docs/modules/ROOT/pages/references/parameters.adoc
> +Dict that creates JobFailed alert rules for the given types of jobs.
```suggestion
Dict which controls the set of JobFailed alert rules to create.
```

2021-08-03 12:56 UTC, simu commented on docs/modules/ROOT/pages/references/parameters.adoc
> +type:: dict
```suggestion
type:: dict
valid keys:: `['archive', 'backup', 'check', 'prune', 'restore']`
```

2021-08-03 12:56 UTC, simu commented on docs/modules/ROOT/pages/references/parameters.adoc
> +Valid keys are `archive`, `backup`, `check`, `prune`, and `restore`.
```suggestion
Valid keys are `archive`, `backup`, `check`, `prune`, and `restore`.
The value for each key is expected to be a dict with keys `enabled` and `overrides`.
```

2021-08-03 12:56 UTC, simu commented on docs/modules/ROOT/pages/references/parameters.adoc
> +`enabled: false` removes the alert rule.
```suggestion
The value for key `enabled` should be a boolean.
This key controls whether the corresponding alert rule is created.
```

2021-08-03 12:56 UTC, simu commented on docs/modules/ROOT/pages/references/parameters.adoc
> +Overrides can override all fields from the `job_failed_alert_template`.
```suggestion
The value for key `overrides` is merged with the object configured in `job_failed_alert_template`.
When configuring overrides, Jsonnet merges arrays and objects from the template with their counterparts in `overrides`.
This key allows users to customize any alert properties for individual `JobFailed` alerts.
```

2021-08-03 12:56 UTC, simu commented on docs/modules/ROOT/pages/references/parameters.adoc
> +default:: See https://github.com/projectsyn/component-backup-k8up/blob/master/class/defaults.yml
```suggestion
default:: [See `class/defaults.yml`|https://github.com/projectsyn/component-backup-k8up/blob/master/class/defaults.yml]
```

2021-08-03 12:56 UTC, simu commented on docs/modules/ROOT/pages/references/parameters.adoc
> +default:: See https://github.com/projectsyn/component-backup-k8up/blob/master/class/defaults.yml
```suggestion
default:: [See `class/defaults.yml`|https://github.com/projectsyn/component-backup-k8up/blob/master/class/defaults.yml]
```

2021-08-03 12:56 UTC, simu commented on docs/modules/ROOT/pages/references/parameters.adoc
> -global_keepjobs: "1"
What would the equivalent(-ish) config to `global_keepjobs=1` be with the new parameters? Might be a good idea to show here.

2021-08-03 13:14 UTC, bastjan commented on component/monitoring.jsonnet
> +    }
🧙‍♂️

2021-08-03 14:04 UTC, bastjan commented on docs/modules/ROOT/pages/references/parameters.adoc
> -global_keepjobs: "1"
Fixed it in b53f6b9bc2b2467ad1eb94153d5e0d7f445e9a35. But I would remove everything other than `monitoring_alerts` to be honest. The values were old/wrong and I don't think the help improve the understanding of the example.

2021-08-03 16:25 UTC, ccremer commented on docs/modules/ROOT/pages/references/parameters.adoc
> +Overridden by `global_backup_config.successful_jobs_history_limit` and `global_backup_config.failed_jobs_history_limit` respectively.
```suggestion
Deprecated: Use `global_backup_config.successful_jobs_history_limit` and `global_backup_config.failed_jobs_history_limit` instead, they override `global_backup_config.keepjobs`.
```

2021-08-06 07:32 UTC, simu approved these changes

2021-08-06 07:35 UTC, ccremer approved these changes

2021-08-06 07:39 UTC, merged