Remove 'enabled' parameter
projectsyn/component-backup-k8up pull request #55
Opened 2021-11-01 15:35 UTC by ccremer

* removes `enabled` parameter. Recent Commodore versions can do it natively.

## Checklist

- [x] Keep pull requests small so they can be easily reviewed.
- [x] Update the documentation.
- [x] Categorize the PR by setting a good title and adding one of the labels:
      `bug`, `enhancement`, `documentation`, `change`, `breaking`, `dependency`
      as they show up in the changelog

2021-11-01 15:56 UTC, simu reviewed
The `enabled` parameter is still required because we include `backup-k8up` at the `cloud` level for some clouds (e.g. https://git.vshn.net/syn/commodore-defaults/-/blob/master/cloud/cloudscale/params.yml), but want to disable the component at the `distribution` level (e.g. https://git.vshn.net/syn/commodore-defaults/-/blob/master/distribution/openshift3.yml).

For this scenario, the native Commodore feature of removing the component by adding `~backup-k8up` to the applications array in `distribution/openshift3.yml` doesn't work, because `distribution` is included before `cloud` and application removals are processed eagerly for each included class.

2021-11-01 16:00 UTC, simu requested changes
If you want to go ahead and remove the parameter, please make it a non-breaking change as sketched out in the inline comment.

2021-11-01 16:15 UTC, ccremer commented on component/app.jsonnet
> +{
This PR is meant to be separate from #56 in order to have a dedicated changelog entry.
Nevertheless, #56 will most probably be a breaking change anyway. Do you still think I should deprecate first?

2021-11-03 13:38 UTC, simu approved these changes

2021-11-03 13:42 UTC, merged